=== consultant-1379/adp-ui-service/backend/schemas/ui.config.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "http://adp.ericsson.com/ui.config.json",
  "type": "object",
  "description": "File descriptor for UI micro front-ends.\nThis file includes all apps, components and groups supported by UI micro front-ends.\nThis file should be named 'config.json' and should be accessible from the service root URL.\n",
  "properties": {
    "version": {
      "$id": "http://adp.ericsson.com/ui.config.json#/properties/version",
      "type": "string",
      "description": "Schema version of the config.json."
    },
    "apps": {
      "$id": "http://adp.ericsson.com/ui.config.json#/properties/apps",
      "type": "array",
      "description": "List of applications available as part of the service.",
      "items": {
        "$ref": "ui.app.json"
      }
    },
    "groups": {
      "$id": "http://adp.ericsson.com/ui.config.json#/properties/groups",
      "type": "array",
      "description": "List of groups available as part of the service.",
      "items": {
        "$ref": "ui.entity.json"
      }
    },
    "components": {
      "$id": "http://adp.ericsson.com/ui.config.json#/properties/components",
      "type": "array",
      "description": "List of components available as part of the service.",
      "items": {
        "$ref": "ui.component.json"
      }
    },
    "overrides": {
      "$id": "http://adp.ericsson.com/ui.config.json#/properties/overrides",
      "type": "object",
      "description": "List of config overrides.",
      "items": {
        "$ref": "ui.config.override.json"
      }
    },
    "groupMappings": {
      "$id": "http://adp.ericsson.com/ui.config.json#/properties/groupMappings",
      "type": "array",
      "description": "List of group mapping.",
      "items": {
        "$ref": "ui.config.groupMappings.json"
      }
    },
    "actions": {
      "description": "UI Actions",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "ui.actions.json"
      }
    }
  },
  "additionalProperties": false
}

=== consultant-1379/adp-ui-service/backend/test/mocks/configs/domain-app2.config.json
{
  "apps": [
    {
      "name": "domain-app-2",
      "displayName": "Domain App 2",
      "descriptionLong": "This is a domain specific app",
      "version": "1.0.0",
      "type": "web-client",
      "url": "domain-app-2",
      "tags": ["webapp"],
      "specification": "domain-app-2/spec.json",
      "groupNames": ["domain-group-2"]
    }
  ],
  "components": [
    {
      "name": "component-2",
      "displayName": "Component entities",
      "version": "1.0.0",
      "descriptionLong": "Component entities for MongoDB",
      "type": "json",
      "specification": "component-2/spec.json"
    }
  ],
  "groups": [
    {
      "name": "domain-group-2",
      "displayName": "Domain Group",
      "version": "0.1.0",
      "descriptionLong": "Domain applications",
      "type": "apps"
    }
  ],
  "actions": [
    {
      "id": "eric-eo-usermgmt-ui.view-user-profile-action",
      "displayName": "View User Profile",
      "version": "1.0.0",
      "module": "view-user-action"
    }
  ]
}

=== consultant-1379/adp-ui-service/backend/test/mocks/configs/domain-app1.config.json
{
  "apps": [
    {
      "name": "domain-app-1",
      "displayName": "Domain App 1",
      "descriptionLong": "This is a domain specific app",
      "version": "1.0.0",
      "type": "web-client",
      "url": "domain-app-1",
      "tags": ["webapp"],
      "specification": "domain-app-1/spec.json",
      "groupNames": ["domain-group-1"]
    }
  ],
  "components": [
    {
      "name": "component-1",
      "displayName": "Component entities",
      "version": "1.0.0",
      "descriptionLong": "Component entities for MongoDB",
      "type": "json",
      "specification": "component-1/spec.json"
    }
  ],
  "groups": [
    {
      "name": "domain-group-1",
      "displayName": "Domain Group",
      "version": "0.1.0",
      "descriptionLong": "Domain applications",
      "type": "apps"
    }
  ],
  "actions": [
    {
      "id": "eric-fh-alarm-handler.clear-alarm-action",
      "displayName": "Clear Alarm",
      "shortDescription": "Change the Alarm to Cleared state",
      "longDescription": "Change the Alarm to Cleared state. If the Alarm is already Cleared, throw error message.",
      "icon": "trashcan",
      "version": "1.0.0",
      "module": "clear-alarm-action",
      "group": ["fault-management-group-ID", "group2"],
      "tags": ["alarm"]
    },
    {
      "id": "eric-eo-usermgmt-ui.view-user-profile-action",
      "displayName": "View User Profile",
      "version": "1.0.0",
      "module": "view-user-action"
    },
    {
      "id": "eric-eea-call-browser-service.list-calls-action",
      "displayName": "View Subscriber's Call List",
      "version": "1.0.0",
      "module": "view-subscriber-action",
      "parameters": [
        {
          "name": "url",
          "type": "url_template",
          "value": "https://eea.internal.ericsson.local/callbrowser/query?subscriberimsi={imsi}&startime={timeInterval.start_time}&endtime={timeInterval.end_time}"
        }
      ]
    },
    {
      "id": "eric-eea-call-browser-service.compare-calls-action",
      "displayName": "Compare Multiple Calls",
      "version": "1.0.0",
      "module": "compare-calls-action"
    }
  ]
}
